[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "infoblox-netmri==3.8.0.0",
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "textfsm>=1.1.3",
]
